# --------------------------------------------------
# Prerequisites - What you MUST do BEFORE running:
# --------------------------------------------------
# 1. Install Python: Make sure you have Python installed on your system.
#    You can download it from python.org if you don't.
# 2. Install the gTTS library: Open your terminal or command prompt and run:
#    pip install gTTS
#    (or sometimes 'pip3 install gTTS' depending on your Python setup)
# 3. Internet Connection: Ensure you have an active internet connection,
#    as gTTS needs to contact Google's servers.
# 4. (For Linux users): Ensure 'xdg-utils' is installed for playback.
#    On Debian/Ubuntu: sudo apt update && sudo apt install xdg-utils
#    On Fedora: sudo dnf install xdg-utils
#    Check your specific distribution's package manager if different.
# --------------------------------------------------

import os   # Used for interacting with the operating system (like running commands)
import sys  # Used to check the operating system type (Windows, macOS, Linux)

# Import the core gTTS class from the gtts library you installed
try:
    from gtts import gTTS
    from gtts.tts import gTTSError  # Import specific gTTS error for better handling
except ImportError:
    print("ERROR: The 'gTTS' library is not installed.")
    print("Please install it by running 'pip install gTTS' in your terminal.")
    sys.exit(1) # Exit the script if gTTS isn't found

# --- Configuration ---
text_to_speak = "Welcome to the world of Text-to-Speech using Python!" # The text you want to convert
language_code = "en"  # Language code (e.g., 'en' for English, 'es' for Spanish, 'fr' for French)
output_filename = "output_speech.mp3" # The name for the MP3 file that will be saved
slow_speech = False # Set to True if you want the speech to be slower

print("Starting Text-to-Speech conversion...")

# --- Generate Speech ---
try:
    # Create the gTTS object
    # - text: The string of text to be spoken.
    # - lang: The language code for the speech.
    # - slow: Whether to use a slower speech speed.
    speech_object = gTTS(text=text_to_speak,
                         lang=language_code,
                         slow=slow_speech)

    # Save the audio generated by the gTTS object to an MP3 file
    speech_object.save(output_filename)
    print(f"Audio successfully saved as '{output_filename}'")

    # --- Play the Saved File ---
    print(f"Attempting to play '{output_filename}'...")

    # Check the operating system and use the appropriate command to open the file
    if sys.platform == "win32":
        # Windows: Use the 'start' command
        os.system(f"start {output_filename}")
    elif sys.platform == "darwin":
        # macOS: Use the 'open' command
        os.system(f"open {output_filename}")
    else:
        # Linux and other Unix-like systems: Use 'xdg-open'
        # This command uses the system's default application for the file type.
        return_code = os.system(f"xdg-open {output_filename}")
        if return_code != 0:
            print(f"Warning: 'xdg-open' command might have failed (exit code: {return_code}).")
            print("Ensure 'xdg-utils' is installed and a default MP3 player is configured.")

except gTTSError as e:
    print(f"A gTTS Error occurred: {e}")
    print("This might be due to network issues, invalid language code, or problems reaching Google's TTS service.")
except PermissionError:
    print(f"Error: Permission denied to save the file '{output_filename}'.")
    print("Please run the script in a directory where you have write permissions.")
except Exception as e:
    # Catch any other unexpected errors during saving or playing
    print(f"An unexpected error occurred: {e}")
    print("Could not save or play the file. Check permissions, library installation, internet connection, and playback commands.")

print("Script finished.")